#!/usr/bin/perl -wT
use CGI qw(:standard);

print "Content-type: text/html\n\n";
print << endOfHtml;
<html><head><title>Hello World!</title></head>
<body>
h2>Hello, World!</h2>
</body></html>
endOfHtml